# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SpeakScan Voice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'FSPagerView'
pod 'lottie-ios'
pod 'FrostedSidebar'

  # Pods for SpeakScan Voice

end
